baseURL = 'https://eshirvana.github.io'
languageCode = 'en-us'
title = 'ehsan shirvanian'
theme = "hello-friend-ng"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.


[author]
  name = "ehsan shirvanian"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "a data engineer, traveller, photographer"
  # homeSubtitle = "exploring the world one bit at a time."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My homepage"
  keywords = "homepage, blog"
  images = [""]
  #backgroundImage = "https://source.unsplash.com/featured/1920x1080/"

  enableThemeToggle = true
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Ehsan Shirvanian"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark     = " "
      logoText = "ehsan@home:~$"
      logoHomeLink = "/"
      
# [params.portrait]
#   path     = "https://avatars.githubusercontent.com/u/72626662?v=4"
#   alt      = "Portrait"
#   maxWidth = "150px"

[[params.social]]
  name = "github"
  url = "https://github.com/eshirvana/"

[[params.social]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/1367454/eshirvana"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/eshirvana/"

[[params.social]]
    name = "instagram"
    url  = "https://instagram.com/eshirvana/"

[[params.social]]
    name = "email"
    url  = "mailto:ehsan@duck.com"



[menu]
  [[menu.main]]
    identifier = "about"
    name       = "~/about"
    url        = "/about"

  # [[menu.main]]
  #   identifier = "posts"
  #   name       = "~/posts"
  #   url        = "posts/"

[params.footer]
  trademark = true
  author = false
  bottomText = ["exploring the world one bit at a time."]

