baseURL = 'https://eshirvana.github.io'
languageCode = 'en-us'
#defaultContentLanguage = 'fr'
title = 'ehsan shirvanian'
theme = "hello-friend-ng"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = 'All Rights Reserved.'

[params]
    [params.author]
      name = "ehsan shirvanian"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  # homeSubtitle = "data engineer, traveler, photographer"
  # homeSubtitle = "exploring the world one bit at a time."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My homepage"
  keywords = "homepage, blog,Ehsan Shirvanian, ehsan, shirvanian"
  images = [""]
  #backgroundImage = "https://source.unsplash.com/featured/1920x1080/"


  enableThemeToggle = true

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    [languages.en.params]
      title = "Ehsan Shirvanian"
      homeSubtitle = "data engineer, traveler, photographer"
      homeSubtitle2 = "data engineer, traveler, photographer"
      keywords = ""
      readOtherPosts = "Read other posts"
      weight = 1
      [languages.en.params.logo]
        logoMark     = " "
        logoText = "ehsan@home:~$"
        logoHomeLink = "/"
      
  [languages.fr]
    [languages.fr.params]
      title = "Ehsan Shirvanian"
      homeSubtitle = "Ingénieur de données, voyageur, photographe"
      keywords = ""
      readOtherPosts = "Read other posts"
      weight    = 2
      [languages.fr.params.logo]
        logoMark     = " "
        logoText = "ehsan@home:~$"
        logoHomeLink = "/"

# [params.portrait]
#   path     = "https://avatars.githubusercontent.com/u/72626662?v=4"
#   alt      = "Portrait"
#   maxWidth = "150px"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/shirvanian/"

[[params.social]]
  name = "github"
  url = "https://github.com/eshirvana/"

[[params.social]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/u/1367454/"

[[params.social]]
    name = "instagram"
    url  = "https://instagram.com/eshirvana/"

[[params.social]]
    name = "email"
    url  = "mailto:ehsan@duck.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "~/about"
    url        = "/about"

  # [[menu.main]]
  #   identifier = "posts"
  #   name       = "~/posts"
  #   url        = "posts/"

[params.footer]
  trademark = false
  author = false
  copyright= false
  topText = ['<a href="https://www.womenlifefreedom.com/" target="_blank" style="text-decoration: none" rel="external">#womanlifefreedom</a>']
  bottomText = ["exploring the world one bit at a time."]

